#!/usr/bin/env node

// 本機測試 host 的 runtime 供檔:依 matcha-assets.json runtime 區塊(由
// platform/build-matcha-lexicon.mjs 的 runtimeManifest 從 node_modules 計算)
// 把 ORT 與 lamejs 以 packName 複製到 mobile-host/vendor/runtime/,等同下游
// 從 npm 取檔後以 packName 供檔的形狀;kaldifst dist 複製到 vendor/kaldifst/。
// 另寫 vendor/runtime-manifest.js 給 service worker importScripts 取得清單。

import {copyFileSync, mkdirSync, readdirSync, rmSync, writeFileSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

import {RUNTIME_FILES, runtimeManifest} from '../platform/build-matcha-lexicon.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const output = path.join(root, 'mobile-host', 'vendor');
const runtimeDir = path.join(output, 'runtime');

mkdirSync(runtimeDir, {recursive: true});
mkdirSync(path.join(output, 'kaldifst'), {recursive: true});
// 舊版本的 packName 不再服務,清掉避免 vendor 目錄累積。
for (const stale of readdirSync(runtimeDir)) rmSync(path.join(runtimeDir, stale));
for (const legacy of ['ort', 'lame.min.js', 'opencc-t2cn.js']) rmSync(path.join(output, legacy), {recursive: true, force: true});

const runtime = runtimeManifest(root);
const packNames = [];
for (const {pkg, file} of RUNTIME_FILES) {
  const {packName} = runtime[pkg].files[file];
  copyFileSync(path.join(root, 'node_modules', pkg, file), path.join(runtimeDir, packName));
  packNames.push(packName);
}

for (const file of ['matcha-kaldifst-normalizer.js', 'matcha-kaldifst-normalizer.wasm']) {
  copyFileSync(
    path.join(root, 'platform', 'kaldifst-wasm', 'dist', file),
    path.join(output, 'kaldifst', file),
  );
}

const versions = Object.fromEntries(Object.entries(runtime).map(([pkg, {version}]) => [pkg, version]));
writeFileSync(path.join(output, 'versions.json'), `${JSON.stringify(versions, null, 2)}\n`);
writeFileSync(
  path.join(output, 'runtime-manifest.js'),
  `// generated by scripts/vendor-mobile.mjs\nself.WASMTTS_RUNTIME_FILES = ${JSON.stringify(packNames.map((name) => `/mobile-host/vendor/runtime/${name}`))};\n`,
);
console.log(`已準備 mobile runtime：${Object.entries(versions).map(([name, version]) => `${name}@${version}`).join('、')} → ${packNames.join('、')}`);
